### Create Report
POST  http://localhost:3000/reports
Content-Type: 'application/json'

{
    "mark": "toyota",
    "model": "corrola",
    "year": 1980,
    "mileage": 100000,
    "lon": 0,
    "lat": 0,
    "price": 50000
}
### Approve Report
PATCH   http://localhost:3000/reports/1/approve
Content-Type: 'application/json'

{
    "approved": true
}