POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "admin@mail.com",
    "password": "adminadmin"
} 

### 
GET  http://localhost:3000/auth/

###
GET  http://localhost:3000/auth/1