### Registration
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "admin2@mail.com",
    "password": "adminadmin"
} 
### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "admin2@mail.com",
    "password": "adminadmin"
} 
### signout
POST http://localhost:3000/auth/signout
### WhoAmI
GET  http://localhost:3000/auth/whoami

### 
GET  http://localhost:3000/auth

###
GET  http://localhost:3000/auth/1

###Updagte
PATCH   http://localhost:3000/auth/1
Content-Type: application/json

{
    "password": "adminadmin"
} 

### Delete
DELETE http://localhost:3000/auth/1